#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Conta/AutenticacaoExternaFalha.cshtml")]
    public partial class _Views_Conta_AutenticacaoExternaFalha_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Conta_AutenticacaoExternaFalha_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Conta\AutenticacaoExternaFalha.cshtml"
  
    ViewBag.Title = "Autenticação falhou";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup>\r\n    <h2>");

            
            #line 6 "..\..\Views\Conta\AutenticacaoExternaFalha.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h2>\r\n    <h3");

WriteLiteral(" class=\"text-error\"");

WriteLiteral(">Autenticação com o serviço mal sucedido.</h3>\r\n</hgroup>\r\n");

        }
    }
}
#pragma warning restore 1591
