#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Conta/ConfirmarEmail.cshtml")]
    public partial class _Views_Conta_ConfirmarEmail_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Conta_ConfirmarEmail_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Conta\ConfirmarEmail.cshtml"
  
    ViewBag.Title = "Email confirmado";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 5 "..\..\Views\Conta\ConfirmarEmail.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h2>\r\n<div>\r\n    <p>\r\n        Obrigado por confirmar o seu e-mail. Por favor ");

            
            #line 8 "..\..\Views\Conta\ConfirmarEmail.cshtml"
                                                  Write(Html.ActionLink("clique aqui para entrar", "Entrar", "Conta", routeValues: null, htmlAttributes: new { id = "entrarLink" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </p>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
