#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Conta/Entrar.cshtml")]
    public partial class _Views_Conta_Entrar_cshtml : System.Web.Mvc.WebViewPage<AspNet.Identity.Common.ViewModels.EntrarViewModel>
    {
        public _Views_Conta_Entrar_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Conta\Entrar.cshtml"
  
    ViewBag.Title = "Entrar";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup>\r\n    <h2>");

            
            #line 8 "..\..\Views\Conta\Entrar.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h2>\r\n</hgroup>\r\n<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"col-md-8\"");

WriteLiteral(">\r\n        <section");

WriteLiteral(" id=\"loginForm\"");

WriteLiteral(">\r\n");

            
            #line 13 "..\..\Views\Conta\Entrar.cshtml"
            
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Conta\Entrar.cshtml"
             using (Html.BeginForm("Entrar", "Conta", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Conta\Entrar.cshtml"
           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Conta\Entrar.cshtml"
                                        

            
            #line default
            #line hidden
WriteLiteral("                <h4>Usar uma conta local para entrar.</h4>\r\n");

WriteLiteral("                    <hr />\r\n");

            
            #line 18 "..\..\Views\Conta\Entrar.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Conta\Entrar.cshtml"
               Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Conta\Entrar.cshtml"
                                                                                     

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 20 "..\..\Views\Conta\Entrar.cshtml"
                   Write(Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 22 "..\..\Views\Conta\Entrar.cshtml"
                       Write(Html.TextBoxFor(m => m.Email, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 23 "..\..\Views\Conta\Entrar.cshtml"
                       Write(Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 27 "..\..\Views\Conta\Entrar.cshtml"
                   Write(Html.LabelFor(m => m.Senha, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                            ");

            
            #line 29 "..\..\Views\Conta\Entrar.cshtml"
                       Write(Html.PasswordFor(m => m.Senha, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                            ");

            
            #line 30 "..\..\Views\Conta\Entrar.cshtml"
                       Write(Html.ValidationMessageFor(m => m.Senha, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n");

WriteLiteral("                                ");

            
            #line 36 "..\..\Views\Conta\Entrar.cshtml"
                           Write(Html.CheckBoxFor(m => m.LembrarMe));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                ");

            
            #line 37 "..\..\Views\Conta\Entrar.cshtml"
                           Write(Html.LabelFor(m => m.LembrarMe));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n           " +
"         </div>\r\n");

WriteLiteral("                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

WriteLiteral(">\r\n                            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"Entrar\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" />\r\n                        </div>\r\n                    </div>\r\n");

WriteLiteral("                    <p>\r\n");

WriteLiteral("                        ");

            
            #line 47 "..\..\Views\Conta\Entrar.cshtml"
                   Write(Html.ActionLink("Registrar novo usuário?", "Registrar"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </p>\r\n");

WriteLiteral("                    <p>\r\n");

WriteLiteral("                        ");

            
            #line 50 "..\..\Views\Conta\Entrar.cshtml"
                   Write(Html.ActionLink("Recuperar sua senha?", "RecuperarSenha"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </p>\r\n");

            
            #line 52 "..\..\Views\Conta\Entrar.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </section>\r\n    </div>\r\n    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n        <section");

WriteLiteral(" id=\"socialLoginForm\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 57 "..\..\Views\Conta\Entrar.cshtml"
       Write(Html.Partial("_AutenticacoesExternasListaPartial", new AspNet.Identity.Common.ViewModels.AutenticacaoExternaListaViewModel { ReturnUrl = ViewBag.ReturnUrl }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </section>\r\n    </div>\r\n</div>\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 62 "..\..\Views\Conta\Entrar.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
