#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Conta/ExibirEmail.cshtml")]
    public partial class _Views_Conta_ExibirEmail_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Conta_ExibirEmail_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Conta\ExibirEmail.cshtml"
  
    ViewBag.Title = "Demonstração do link enviado para o Email";

            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>");

            
            #line 4 "..\..\Views\Conta\ExibirEmail.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h2>\r\n<p");

WriteLiteral(" class=\"text-info\"");

WriteLiteral(">\r\n    Por favor, verifique seu e-mail e confirme o seu endereço de e-mail.\r\n</p>" +
"\r\n<p");

WriteLiteral(" class=\"text-danger\"");

WriteLiteral(">\r\n    Por apenas demonstração: Você pode clicar nesse link para confirmar o e-ma" +
"il: <a");

WriteAttribute("href", Tuple.Create(" href=\"", 311), Tuple.Create("\"", 331)
            
            #line 9 "..\..\Views\Conta\ExibirEmail.cshtml"
            , Tuple.Create(Tuple.Create("", 318), Tuple.Create<System.Object, System.Int32>(ViewBag.Link
            
            #line default
            #line hidden
, 318), false)
);

WriteLiteral(">link</a>.\r\n    Por favor, altere este código para registrar um serviço de e-mail" +
" no IdentityConfig para enviar um e-mail.\r\n</p>\r\n");

        }
    }
}
#pragma warning restore 1591
