#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/AdministracaoUsuarios/Criar.cshtml")]
    public partial class _Views_AdministracaoUsuarios_Criar_cshtml : System.Web.Mvc.WebViewPage<AspNet.Identity.Samples.Common.ViewModels.RegistrarViewModel>
    {
        public _Views_AdministracaoUsuarios_Criar_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
  
    ViewBag.Title = "Criar";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 6 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h2>\r\n\r\n");

            
            #line 8 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
 using (Html.BeginForm("Criar", "UsersAdmin", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
                            

            
            #line default
            #line hidden
WriteLiteral("    <h4>Create a new account.</h4>\r\n");

WriteLiteral("    <hr />\r\n");

            
            #line 13 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
Write(Html.ValidationSummary("", new { @class = "text-error" }));

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
                                                              

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 15 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
   Write(Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 17 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
       Write(Html.TextBoxFor(m => m.Email, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 21 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
   Write(Html.LabelFor(m => m.Senha, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 23 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
       Write(Html.PasswordFor(m => m.Senha, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 27 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
   Write(Html.LabelFor(m => m.SenhaConfirmacao, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 29 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
       Write(Html.PasswordFor(m => m.SenhaConfirmacao, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <label");

WriteLiteral(" class=\"col-md-2 control-label\"");

WriteLiteral(">\r\n            Selecione um grupo pro usuário\r\n        </label>\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

            
            #line 37 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
            
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
             foreach (var item in (SelectList)ViewBag.RoleId)
            {

            
            #line default
            #line hidden
WriteLiteral("                <input");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" name=\"SelectedRoles\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1479), Tuple.Create("\"", 1498)
            
            #line 39 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
, Tuple.Create(Tuple.Create("", 1487), Tuple.Create<System.Object, System.Int32>(item.Value
            
            #line default
            #line hidden
, 1487), false)
);

WriteLiteral(" class=\"checkbox-inline\"");

WriteLiteral(" />\r\n");

            
            #line 40 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
                
            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
           Write(Html.Label(item.Value, new { @class = "control-label" }));

            
            #line default
            #line hidden
            
            #line 40 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
                                                                         
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" value=\"Criar\"");

WriteLiteral(" />\r\n        </div>\r\n    </div>\r\n");

            
            #line 49 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 52 "..\..\Views\AdministracaoUsuarios\Criar.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
