#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Conta\_AutenticacoesExternasListaPartial.cshtml"
    using Microsoft.Owin.Security;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Conta/_AutenticacoesExternasListaPartial.cshtml")]
    public partial class _Views_Conta__AutenticacoesExternasListaPartial_cshtml : System.Web.Mvc.WebViewPage<AspNet.Identity.Samples.Common.ViewModels.AutenticacaoExternaListaViewModel>
    {
        public _Views_Conta__AutenticacoesExternasListaPartial_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<h4>Usar outro serviço de autenticação</h4>\r\n<hr />\r\n");

            
            #line 6 "..\..\Views\Conta\_AutenticacoesExternasListaPartial.cshtml"
  
    var loginProviders = Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes();
    if (loginProviders.Count() == 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div>\r\n            <p>\r\n                Não existem serviços de autentica" +
"ção externos configurados.\r\n                Consulte <a");

WriteLiteral(" href=\"http://go.microsoft.com/fwlink/?LinkId=313242\"");

WriteLiteral(">este</a> artigo\r\n                para obter detalhes sobre a configuração desse " +
"aplicativo ASP.NET para apoiar\r\n                a autenticação através de serviç" +
"os externos.\r\n\r\n            </p>\r\n        </div>\r\n");

            
            #line 19 "..\..\Views\Conta\_AutenticacoesExternasListaPartial.cshtml"
    }
    else
    {
        using (Html.BeginForm("AutenticacaoExterna", "Conta", new { ReturnUrl = Model.ReturnUrl }))
        {
            
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Conta\_AutenticacoesExternasListaPartial.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Conta\_AutenticacoesExternasListaPartial.cshtml"
                                    

            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" id=\"socialLoginList\"");

WriteLiteral(">\r\n                <p>\r\n");

            
            #line 27 "..\..\Views\Conta\_AutenticacoesExternasListaPartial.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 27 "..\..\Views\Conta\_AutenticacoesExternasListaPartial.cshtml"
                     foreach (AuthenticationDescription p in loginProviders)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteAttribute("id", Tuple.Create(" id=\"", 1125), Tuple.Create("\"", 1151)
            
            #line 29 "..\..\Views\Conta\_AutenticacoesExternasListaPartial.cshtml"
, Tuple.Create(Tuple.Create("", 1130), Tuple.Create<System.Object, System.Int32>(p.AuthenticationType
            
            #line default
            #line hidden
, 1130), false)
);

WriteLiteral(" name=\"provider\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1168), Tuple.Create("\"", 1197)
            
            #line 29 "..\..\Views\Conta\_AutenticacoesExternasListaPartial.cshtml"
                                        , Tuple.Create(Tuple.Create("", 1176), Tuple.Create<System.Object, System.Int32>(p.AuthenticationType
            
            #line default
            #line hidden
, 1176), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 1198), Tuple.Create("\"", 1242)
, Tuple.Create(Tuple.Create("", 1206), Tuple.Create("Log", 1206), true)
, Tuple.Create(Tuple.Create(" ", 1209), Tuple.Create("in", 1210), true)
, Tuple.Create(Tuple.Create(" ", 1212), Tuple.Create("using", 1213), true)
, Tuple.Create(Tuple.Create(" ", 1218), Tuple.Create("your", 1219), true)
            
            #line 29 "..\..\Views\Conta\_AutenticacoesExternasListaPartial.cshtml"
                                                                                       , Tuple.Create(Tuple.Create(" ", 1223), Tuple.Create<System.Object, System.Int32>(p.Caption
            
            #line default
            #line hidden
, 1224), false)
, Tuple.Create(Tuple.Create(" ", 1234), Tuple.Create("account", 1235), true)
);

WriteLiteral(">");

            
            #line 29 "..\..\Views\Conta\_AutenticacoesExternasListaPartial.cshtml"
                                                                                                                                                                                       Write(p.AuthenticationType);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 30 "..\..\Views\Conta\_AutenticacoesExternasListaPartial.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </p>\r\n            </div>\r\n");

            
            #line 33 "..\..\Views\Conta\_AutenticacoesExternasListaPartial.cshtml"
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
