#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Conta/RedefinirSenhaConfirmacao.cshtml")]
    public partial class _Views_Conta_RedefinirSenhaConfirmacao_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Conta_RedefinirSenhaConfirmacao_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Conta\RedefinirSenhaConfirmacao.cshtml"
  
    ViewBag.Title = "Redefinir senha confirmação";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<hgroup");

WriteLiteral(" class=\"title\"");

WriteLiteral(">\r\n    <h1>");

            
            #line 6 "..\..\Views\Conta\RedefinirSenhaConfirmacao.cshtml"
   Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h1>\r\n</hgroup>\r\n<div>\r\n    <p>\r\n        Sua senha foi redefinida. Por favor ");

            
            #line 10 "..\..\Views\Conta\RedefinirSenhaConfirmacao.cshtml"
                                       Write(Html.ActionLink("clique aqui para entrar", "Entrar", "Conta", routeValues: null, htmlAttributes: new { id = "entrarLink" }));

            
            #line default
            #line hidden
WriteLiteral("        \r\n    </p>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
